---
title: "R Intro Workshop"
author: "The Cuddington Lab"
date: "`r format(Sys.time(), '%d %B, %Y')`"
site: bookdown::bookdown_site
output:
  bookdown::gitbook:
    highlight: monochrome
    config:
      toc:
        collapse: section

documentclass: book

github-repo: rstudio/bookdown-demo
description: "Building Skills in Quantitative Biology"
---
`
```{r setup, include=FALSE}
knitr::opts_chunk$set(tidy.opts = list(width.cutoff = 60), tidy = TRUE, echo=FALSE, comment="",fig.pos = "H", out.extra = "")
soln=FALSE
```


#  Welcome to our Workshop!

Before the workshop, please check out [Get ready for the workshop]. We would like you to download and install some files before the Workshop

During the workshop, we will complete coding exercises that correspond to the [Learning objectives] below. We will focus on importing data, subsetting the data, completing various regression analysis and creating simple graphs. During the workshop this document will be available for you to copy code etc.

After the workshop we will provide a more detailed version of this accompanying website.

## Learning objectives
 
* Import, check and summarize data in R 
* Create graphs to visualize data and models
* Apply linear, multiple and logistic regression models using R  
* Interpret model fits and results  
* Use simple principal component analyses